### ISSUE TITLE
Issue with running with react 16

### ISSUE THREAD

**Issue by dzz828** [nhabuiduc/react-filter-box#12]
I try to use react-filter-box, but I am getting the following error. I think it is because of my react version is 16 and library depends on react 15. Could you please update it or change it to peer dependency?

Uncaught Error: Element ref was specified as a string (textarea) but no owner was set. This could happen for one of the following reasons:
1. You may be adding a ref to a functional component
2. You may be adding a ref to a component that was not created inside a component's render method
3. You have multiple copies of React loaded

**Comment by nhabuiduc** [comment]
I've just updated all libraries to latest version (and React 16), can you try again
