### ISSUE TITLE
Debugging logs being printed in Console

### ISSUE THREAD

**Issue by krconv** [nhabuiduc/react-filter-box#16]
I'm using the project, and have noticed that there are some debug logs that are getting printed to the client's console as the text is entered into the box. It is difficult to use this in a larger project because I feel that the logs are verbose, and don't correlate to something going wrong. I think these are the three instances in the production code:
 - https://github.com/nhabuiduc/react-filter-box/blob/99dc45181b7e8fc9c0b099983944487df26991e3/src/FilterQueryParser.ts#L41
 - https://github.com/nhabuiduc/react-filter-box/blob/99dc45181b7e8fc9c0b099983944487df26991e3/src/FilterQueryParser.ts#L52
 - https://github.com/nhabuiduc/react-filter-box/blob/c8b089f2f4e796603314dffe84da9890cfb603b4/src/BaseAutoCompleteHandler.ts#L34

Can these debug statements be removed?

**Comment by krconv** [comment]
I'd be willing to make a PR if you agree that this is a problem

**Comment by nhabuiduc** [comment]
Agree, please make PR and I will merge it.
