### ISSUE TITLE
Distributed files include `eval()` which causes errors in some environments

### ISSUE THREAD

**Issue by krconv** [nhabuiduc/react-filter-box#18]
**Problem**: Cannot deploy `react-filter-box` in environments that use the [`unsafe-eval`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#Sources) [Content Security Policy](https://w3c.github.io/webappsec-csp/).

```javascript
react-dom.production.min.js:198 EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self'".

    at compile (react-filter-box.js:9)
    at compileCondition (react-filter-box.js:9)
    ...
```

**Cause**: The Grammar (`src/grammar.pegjs`) parser is compiled at runtime by `pegjs`, which requires the use of `eval(...)`.

**Comment by krconv** [comment]
`pegjs` also provides a method for compiling the grammar ahead of time so that the client doesn't need to; I've tested this a bit and it seems to work. 
It uses the [`pegjs` CLI](https://pegjs.org/documentation#generating-a-parser), and it creates a JS file that could get checked in and distributed with the rest of the code. It could also use [`ts-pegjs`](https://github.com/metadevpro/ts-pegjs) on top of that to create a TypeScript parser instead.

I'd be willing to make a PR if you think that this is a problem that should be addressed.

**Comment by nhabuiduc** [comment]
There is another approach which creates a Custom Loader (Babel loader), in that custom loader we run pegjs library to generate Javascript code from grammar file.

With this approach we don't need to run pegjs cli everytime Grammar file changed.

Original code
```typescript
var grammar: string = require<string>("raw-loader!./grammar.pegjs");
var parser: ExtendedParser = <ExtendedParser>PEG.generate(grammar);
```

would become
```typescript
var parser: ExtendedParser = require<ExtendedParser>("my-custom-loader!./grammar.pegjs");
```

**Comment by krconv** [comment]
I kinda like the idea of being able to see that file, but I wouldn't be thrilled that a generated file would be in source control. I'm fine with either way, that as long as we can get the `eval(..)`s out.

I can create a PR for this with the web pack approach if that's helpful

**Comment by nhabuiduc** [comment]
Yes, please create PR, i will merge it. Thanks
