### ISSUE TITLE
Option to parse numeric values

### ISSUE THREAD

**Issue by krconv** [nhabuiduc/react-filter-box#20]
Is it possible to use the `type` in `options` for a column to have it automatically parsed? For example, is there any way to get a number back from the filter instead of the string that the user typed in?
```js
const options = [
  {
    columnField: 'SourcePort',
    type: 'number'
  }
];

const handleQueryChange = (expressions) => {
  // Proposed: expressions[0].value is a number, because it was automatically parsed
};

return <ReactFilterBox onChange={handleQueryChage} options={options} />
```

**Comment by krconv** [comment]
Or maybe, an option `converter` that is a function that can be used to translate the value from what the user typed into another type. I want to use this filter on a remote server, and I need to be able to translate the values before sending them.
```js
const options = [
  {
    columnField: 'SourcePort',
    type: 'text',
    converter: parseInt
  }
];

**Comment by krconv** [comment]
I'd be willing to create a PR if you feel it is a worthy feature

**Comment by nhabuiduc** [comment]
`Expression` is used to represent Syntax Tree Structure only, it does not have any idea about data type. It's up to user to use that expression (if we add datatype then it needs to handle wrong data input, which is not its job). For example with `SimpleResultProcessing`, it combine options and expression to transform data as below:

```
var newData = new SimpleResultProcessing(this.options).process(data, expressions);
```

I think in your case, you just need to write a class to transform `Expression` to your `CustomExpression` with passed `options`. (Expression has columnField, it should be easy to know which field is `number`)

**Comment by krconv** [comment]
Thanks for the pointer; that works for me 👍
