### ISSUE TITLE
Does this library support grater than or less than conditions?

### ISSUE THREAD

**Issue by nuwanprabhath** [nhabuiduc/react-filter-box#3]
Example age > 25

**Comment by nhabuiduc** [comment]
It's not support by default, but it's very easy to add your own operator (>) or whatever, example on demo site: https://nhabuiduc.github.io/

And source for custom operator (example here is 'after' operator): https://github.com/nhabuiduc/react-filter-box/blob/master/js-example/src/demo3.js
