### ISSUE TITLE
Multiple (conflicting) copies of React loaded

### ISSUE THREAD

**Issue by AchinthaReemal** [nhabuiduc/react-filter-box#4]
I get the following error when adding the ReactFilterBox component to another react component class.

> Uncaught Error: removeComponentAsRefFrom(...): Only a ReactOwner can have refs. You might be removing a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded

**Comment by mstmustisnt** [comment]
@AchinthaReemal this can happen when you already have react in `node_modules`, but it's version differs than `react-filter-box` requires.. as a result `react-filter-box` installs react in own `node_modules`..

**Comment by pablooneto** [comment]
could you change the dependencies? react is now at version 15? in dependencies you have
```
    "react": "^0.14.6",
    "react-codemirror": "^0.2.6",
    "react-dom": "^0.14.6"
```
you could use
```
    "react": "*",
    "react-codemirror": "*",
    "react-dom": "*"
```
or you could use this to ensure the last version but not 16, im using it on 15 and its running ok:
```
    "react": "^15.0.0",
    "react-codemirror": "^15.0.0",
    "react-dom": "^15.0.0",
```

**Comment by nhabuiduc** [comment]
Just upgrade all dependencies to latest versions. 
205437798e168974757ba1c96418d50d4bdef253
