### ISSUE TITLE
Can't load an initial expression

### ISSUE THREAD

**Issue by yuvalpeled2** [nhabuiduc/react-filter-box#46]
I'd like to load an initial expression to the component but it seems to be impossible.
In addition, because of the same reason, it's impossible to clear the expression programaticlly.

**Comment by ChandraAvira** [comment]
> I'd like to load an initial expression to the component but it seems to be impossible. In addition, because of the same reason, it's impossible to clear the expression programaticlly.

HI, is there a way to clear the input filed data after the search or on clicking some custom clear filter button
